import React, { useState, useEffect, useRef } from 'react';
import { Header, BarChart, Loading, Error } from '../components/index.js';
import { Trie } from '../trie.js';
import { getBaseUrl } from '../utils/helpers.js';

const BASE_URL = getBaseUrl();

/**
 * KeywordsPage component for displaying all keywords
 */
export function KeywordsPage() {
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);
    const [keywordData, setKeywordData] = useState([]);
    const keywordTrieRef = useRef(new Trie());

    useEffect(() => {
        loadData();
    }, []);

    const loadData = async () => {
        try {
            const response = await fetch(`${BASE_URL}data/agencies_data.json`);
            if (!response.ok) {
                throw new Error(`Failed to load data: ${response.statusText}`);
            }
            
            const allAgencies = await response.json();
            
            // Build keyword trie
            buildKeywordTrie(allAgencies);
            
            // Get all keywords sorted by count
            const allKeywords = keywordTrieRef.current.getAllKeywords();
            setKeywordData(allKeywords.map(k => ({
                label: k.keyword,
                count: k.count,
                linkUrl: `${BASE_URL}?keywords=${encodeURIComponent(k.keyword)}`,
                tooltip: `View documents with keyword: ${k.keyword}`
            })));
            
            setLoading(false);
        } catch (err) {
            console.error('Error loading data:', err);
            setError(`Failed to load data: ${err.message}`);
            setLoading(false);
        }
    };

    const buildKeywordTrie = (allAgencies) => {
        const trie = new Trie();
        
        allAgencies.forEach(agency => {
            if (agency.documents && Array.isArray(agency.documents)) {
                agency.documents.forEach(doc => {
                    if (doc.sir_violation_level?.keywords) {
                        doc.sir_violation_level.keywords.forEach(keyword => {
                            trie.insert(keyword, true, keyword);
                            
                            const words = keyword.trim().split(/\s+/);
                            words.forEach(word => {
                                if (word.length > 0) {
                                    trie.insert(word, false, keyword);
                                }
                            });
                        });
                    }
                });
            }
        });
        
        keywordTrieRef.current = trie;
    };

    if (loading) {
        return (
            <>
                <Header 
                    title="All Keywords" 
                    subtitle="Complete list of keywords from all documents" 
                />
                <div className="container">
                    <Loading message="Loading keywords..." />
                </div>
            </>
        );
    }

    if (error) {
        return (
            <>
                <Header 
                    title="All Keywords" 
                    subtitle="Complete list of keywords from all documents" 
                />
                <div className="container">
                    <Error message={error} />
                </div>
            </>
        );
    }

    return (
        <>
            <Header 
                title="All Keywords" 
                subtitle="Complete list of keywords from all documents" 
            />
            <div className="container">
                <a href={`${BASE_URL}`} className="back-link">← Back to Dashboard</a>
                
                <div className="keywords-container">
                    <div className="keywords-header">
                        <h2>🏷️ All Keywords by Document Count</h2>
                        <p className="keywords-description">
                            This page shows all keywords extracted from Special Investigation Reports,
                            sorted by the number of documents containing each keyword.
                            Click on any keyword to view documents with that keyword.
                        </p>
                        <p className="keywords-description" style={{ 
                            marginTop: '12px',
                            fontSize: '0.85em',
                            color: '#555',
                            lineHeight: 1.6
                        }}>
                            <strong>ℹ️ Note:</strong> Keywords were AI-generated by DeepSeek v3.2 from publicly available report text
                            and may be inconsistent or erroneous. For example, not all cases involving repeat violations are
                            necessarily tagged with the "repeat violation" keyword. Documents may contain multiple keywords, and
                            in rare instances two documents may apply to the same event, so counts are not 100% reliable.
                            Always refer to the full report document that is linked.
                            {' '}<a href="https://github.com/statcom-um/MCYJ-Datapipeline/tree/main/llm_analysis/theming" target="_blank" rel="noopener noreferrer" style={{ color: '#3498db' }}>
                                View AI prompts and methodology
                            </a>.
                        </p>
                    </div>
                    
                    <BarChart 
                        title="All Keywords"
                        data={keywordData}
                    />
                </div>
            </div>
        </>
    );
}

export default KeywordsPage;
