import React from 'react';
import { AiCaution } from './AiCaution.jsx';
import { getBaseUrl } from '../utils/helpers.js';

const BASE_URL = getBaseUrl();

export function AboutSection() {
    return (
        <div className="about-section">
            <h2>About This Dashboard</h2>
            <p>
                This dashboard aggregates publicly available child welfare licensing documents
                from the Michigan Department of Licensing and Regulatory Affairs (LARA).
                It is designed for advocates, researchers, and journalists who want to
                explore trends and surface potential patterns across facilities. While utilizing
                this tool, it is important to remember that licensing investigations reflect
                findings at a specific point in time and do not alone indicate current quality of care.
            </p>
            <p>
                <AiCaution label="AI is used on this site" />{' '}
                Some content on this dashboard — including document summaries, severity classifications,
                and staffing analysis — is generated by artificial intelligence.
                Wherever you see the <AiCaution /> symbol, AI was involved.
                Always refer to the full report document that is linked.
                <a href={`${BASE_URL}ai-methodology.html`} className="about-methodology-link">
                    Learn about our AI methodology →
                </a>
            </p>
            <p>
                Source documents are available through the{' '}
                <a href="https://michildwelfarepubliclicensingsearch.michigan.gov/licagencysrch/" target="_blank" rel="noopener noreferrer">
                    Michigan Child Welfare Public Licensing Search
                </a>.
            </p>
        </div>
    );
}

export default AboutSection;
